name       : haskell-tf-random
version    : 0.5
release    : 4
source     :
    - http://hackage.haskell.org/package/tf-random-0.5/tf-random-0.5.tar.gz : 2e30cec027b313c9e1794d326635d8fc5f79b6bf6e7580ab4b00186dadc88510
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package contains an implementation of a high-quality splittable
    pseudorandom number generator.
description: |
    This package contains an implementation of a high-quality splittable pseudorandom number generator.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-primitive
    - haskell-random
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
